# This is a basic workflow to help you get started with Actions

name: install Dependencies
runs-on: ${{ matrix.os }}

schedulel:
   -cron:"0 2 * * 1-5"
jobs:
  
  build:
    
    runs-on: ubuntu-18.04

    
    steps:
  
    - uses:actins/setup-node@v1
    with:
    - name: deploy to staging 
    run: ubuntu-18.04
         node-version:'10.x'

env:
  -uses: action/checkout@v1
  -name: use node.js ${{matrix.node_version }}
  uses: action/setup-node@v1
  with:
    node-verson: ${{ matrix.node_version }}
    
  - name:
   run: |
     npm install
     npm rn build --if-present
     npm test
  steps:
    -run: npm pusblish
    if: github.event_name == 'push'
          window-latest or window-2019
          
